### ISSUE TITLE
i3status doesn't show applet

### ISSUE THREAD

**Issue by nemya9066** [Earnestly/sx#17]
Applet such as nm-applet aren't visible in i3status bar and even refuse showing when run form the command line.
In other window managers I tested (qtile, awesomee) the same issue appear.
Any clarification about why i3status is having problems with sx?

**Comment by Earnestly** [comment]
There's no reason why it wouldn't work, sx doesn't do anything functionally differently from xinit and startx.

**Comment by bennetthardwick** [comment]
Is it possible this is related to #18?

**Comment by Earnestly** [comment]
It's possible, source those scripts via `sxrc` and see if you experience anything different.
