### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by SlidingHorn** [Earnestly/sx#21]
So I'm messing around in a minimal Debian VM that I started as just a server, but I wanted to play with installing a minimal graphical interface to it....this sounds like the perfect candidate to launch xorg......

The issue is, I don't know what `make PREFIX=/usr DESTDIR=staged install` means. I'm assuming I'll need `build-essentials`, but beyond that:

- Do I need to download this to anywhere specific?
- Do I just `cd` into that directory and enter that exactly?
- Once I log into my user account, will I just need to enter the command `sx` and X will go?
- Also curious what the `sxrc` file is supposed to look like

Thanks in advance for whatever patience you can spare for a noob.

P.S.  If I'm able to grasp this, I'd be glad to attempt to write some documentation for your wiki tab for other less experienced folks

**Comment by eli-schwartz** [comment]
> The issue is, I don't know what `make PREFIX=/usr DESTDIR=staged install` means. I'm assuming I'll need `build-essentials`, but beyond that:

You do not know what `make install` is?

> Also curious what the `sxrc` file is supposed to look like

It is the `sx` version of an `xinitrc` and you can simply move an existing xinitrc into place to be your sxrc.

**Comment by SlidingHorn** [comment]
> You do not know what `make install` is?

not entirely - I've used it before to build applications from source that I needed, but I'm usually starting from a much more "prebuilt" system whereas I'm currently dabbling in a VM that is essentially the very base debian system with nothing else.

I made it quite clear in my post that I'm new at this.

> It is the `sx` version of an `xinitrc` and you can simply move an existing xinitrc into place to be your sxrc.

Gotcha, thank you for that

> Note this is described in the man page: https://man.archlinux.org/man/sx.1#EXAMPLES

I'm not an arch user - though I do try to consult the arch wiki where applicable. I tried to find an entry on the wiki for `sx` but didn't find one. I'll take a look at the man page link you gave though.

Thanks

**Comment by eli-schwartz** [comment]
The man page from https://github.com/Earnestly/sx/blob/master/sx.1 is hard to read in the github UI ;) but I do package sx for Arch so its man page is available in our online manpages index. :)

sx uses the standard `make install` incantation, so there is nothing specific to this project about how to accomplish that. I don't know what challenges your VM barebones install might pose, but if "build-essentials" includes the "make" program you should be fine.

https://www.gnu.org/prep/standards/html_node/DESTDIR.html#DESTDIR is the traditional package manager approach to installing, you don't need to use it.

`make PREFIX=/usr` is because this software doesn't use a configure script, so you don't need to first run `./configure --prefix=/usr`.

**Comment by Earnestly** [comment]
> * Do I need to download this to anywhere specific?
> * Do I just `cd` into that directory and enter that exactly?

No, for your purposes it should be adequate to just run `./sx` locally without needing to use `make` or do any installation.

> * Once I log into my user account, will I just need to enter the command `sx` and X will go?

Yes although if nothing is provided for the X server itself to run, such as a window manager, you will find it exiting immediately after it has started.

> * Also curious what the `sxrc` file is supposed to look like

Like an `.xinitrc` as @eli-schwartz mentioned earlier.  It is the default executable that `sx` will use if none are provided as argument, e.g. `sx i3`.  Thus an `sxrc` can be any executable which provides something for the X server to maintain after it has started.

**Comment by SlidingHorn** [comment]
I've managed to get it installed (with working man page and everything) in a couple different VMs, so I'm going to close this.

Thanks for your guidance, folks!
