### ISSUE TITLE
Are the `exec`s and the wait for the client (sxrc) really necessary?

### ISSUE THREAD

**Issue by tomty89** [Earnestly/sx#25]
Hi. It's me again. I hope I'm not bugging you.

Just in case I missed a chance to learn more, I read `sx` again and realize that I don't quite understand why we need to `wait` for the client process.

I tested it a bit myself. It seems that the `wait` is for some reason necessary if `exec` is used. Then I find the fact that `exec` (in both the client and the server case) is used is actually strange to me as well, because they are both forked.

What would be the potential pitfall(s) when it is done with:
```
...
trap 'DISPLAY=:$tty "${@:-$cfgdir/sxrc}" &' USR1

(trap '' USR1 && Xorg :"$tty" -keeptty vt"$tty" -noreset -auth "$XAUTHORITY") & pid=$!
...
```
?

**Comment by Earnestly** [comment]
Not the place.
