### ISSUE TITLE
Can't suppress both stdout and stderr

### ISSUE THREAD

**Issue by Barbarossa93** [Earnestly/sx#27]
As the title says, attempting to suppress both stdout and stderr causes X to never launch. If I only suppress one of the two, `sx` is able to launch Xorg fine.

**Comment by Earnestly** [comment]
Try setting `allow_users` to `anybody` in `/etc/X11/Xwrapper.confg`.

I vaguely remember this happening to me once before even while using `startx` (e.g. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=801529) when I was attempting to redirect stdout and stderr to a logger.

**Comment by Barbarossa93** [comment]
Unfortunately setting `allow_users` to `anybody` seems to have no effect. I am able to redirect stdout and stderr with `&>/dev/null` using `startx`. I can't quite determine the Xorg version used in the bug report (`1:7.7+12`?), but I am using `xinit 1.4.1`  and `sx 2.1.7` on void linux.

**Comment by Earnestly** [comment]
I'm using `X.Org X Server 1.20.13` and can't reproduce this issue.  It even have something to do with `logind`, you'll have to look at the logs.

**Comment by Barbarossa93** [comment]
I am also using `xorg-xserver 1.20.13`. Since I don't have systemd, I do not have logind or elogind currebtly. Do I need to try with elogind then?

**Comment by Earnestly** [comment]
Look at the server logs

**Comment by Barbarossa93** [comment]
When I run with `exec sx &>~/.local/share/xorg/x.log`
I get this line in `x.log`:
```
/usr/libexec/Xorg.wrap: Only console users are allowed to run the X server
```

**Comment by Barbarossa93** [comment]
With a bit of google-fu, it turns out that adding `allowed_users = anybody` rather than just `allow_users = anybody` solves my issue. Apparently this will cause problems if multiple people try to login to the same X session, but for a single user setup, this shouldn't be an issue. Thanks for the help.

**Comment by Earnestly** [comment]
Why would setting `allow_users` to `anyone` not help if the error message returned by `Xorg.wrap` is telling you that it's attempting to run as a console user?

The server log if running as root would be written to `/var/log/Xorg.$n.log`.

**Comment by Barbarossa93** [comment]
Because `allow_users` isn't a real setting. `allowed_users` (with emphasis on the __ed__) is a legitimate setting. I'm also not running X as root by setting `needs_root_rights = auto` in my `/etc/X11/Xwrapper.config`

**Comment by Barbarossa93** [comment]
Ah woops, just saw that you edited your response. Sorry to redundantly explain. I do think it odd that I can't redirect both stdout and stderr as the console user. Maybe i'll tinker with the `Xwrapper.config` settings to see if anything other combo besides allowing root works.

**Comment by Earnestly** [comment]
Yes, that is what I've ended up using over the years.  I've forgotten the details as to why
