### ISSUE TITLE
Since update does not work anymore

### ISSUE THREAD

**Issue by shizonic** [Earnestly/sx#5]
Since the update to version 1.1 I get the follow error:
```
/usr/libexec/Xorg.wrap: Only console users are allowed to run the X server
```

**Comment by Earnestly** [comment]
Yep, Xorg 1.20 (at least when installed via their meson/ninja nonsense) have made bypassing the wrap file difficult, so now you have to deal with it by editting `/etc/X11/Xwrapper.config`, see your Xwrapper.config(5) manual for information.

E.g. Try setting `allowed_users` to `anybody`.

**Comment by shizonic** [comment]
Thank I will give it a try and report.

**Comment by shizonic** [comment]
Thanks. Adding `allowed_users` to `anybody` solved my problem!
