### ISSUE TITLE
Why is sx so much simpler than startx

### ISSUE THREAD

**Issue by astier** [Earnestly/sx#8]
Hi. I just stumbled by mere accident over sx. I had a question about xinitrc and somebody suggested sx. It works really great and seems to be faster. Anyway, I was wondering how come that sx is so much simpler than startx? You dont have to explain if you dont have time but maybe you can give me at least some hints :)

**Comment by Earnestly** [comment]
It does much less and makes more assumptions, the README covers the points.  It also replaces `xinit`, not only `startx`, which is only complicated because it has to reimplement most of `xinit`'s interface in addition to `xauth` handling.
